"use client";

import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";

import { login, login2FA } from "@/lib/api/auth";
import { AuthShell } from "@/components/AuthShell";
import { Button } from "@/components/ui/button";
import { Form, FormField, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const loginSchema = z.object({ email: z.string().email("Enter a valid email address"), password: z.string().min(1, "Password is required") });
const twoFactorSchema = z.object({ code: z.string().length(6, "Enter a 6-digit code") });
type LoginFormValues = z.infer<typeof loginSchema>;
type TwoFactorFormValues = z.infer<typeof twoFactorSchema>;

export default function LoginPage() {
  const [apiError, setApiError] = useState<string | null>(null);
  const [requiresTwoFactor, setRequiresTwoFactor] = useState(false);
  const [twoFactorToken, setTwoFactorToken] = useState<string | null>(null);
  const loginForm = useForm<LoginFormValues>({ resolver: zodResolver(loginSchema), defaultValues: { email: "", password: "" } });
  const twoFactorForm = useForm<TwoFactorFormValues>({ resolver: zodResolver(twoFactorSchema), defaultValues: { code: "" } });

  const onSubmitLogin = async (data: LoginFormValues) => {
    setApiError(null);
    try {
      const response = await login(data);
      if (response.requiresTwoFactor && response.twoFactorToken) { setRequiresTwoFactor(true); setTwoFactorToken(response.twoFactorToken); return; }
      window.location.assign("/dashboard");
    } catch { setApiError("Invalid email or password"); }
  };

  const onSubmitTwoFactor = async (data: TwoFactorFormValues) => {
    setApiError(null);
    if (!twoFactorToken) return;
    try { await login2FA(twoFactorToken, data.code); window.location.assign("/dashboard"); }
    catch { setApiError("Invalid verification code"); }
  };

  const back = () => { setRequiresTwoFactor(false); setTwoFactorToken(null); setApiError(null); twoFactorForm.reset(); };

  return (
    <AuthShell eyebrow={requiresTwoFactor ? "Identity verification" : "Secure access"} title={requiresTwoFactor ? "Verify it’s you." : "Welcome back."} description={requiresTwoFactor ? "Enter the six-digit code generated by your authenticator app." : "Sign in to enter your IT operations workspace."}>
      {requiresTwoFactor ? (
        <Form {...twoFactorForm}>
          <form className="space-y-5" onSubmit={twoFactorForm.handleSubmit(onSubmitTwoFactor)}>
            <div className="flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/[0.055] p-3 text-xs text-muted-foreground"><ShieldCheck className="size-4 shrink-0 text-primary" />Two-factor protection is enabled for this account.</div>
            <FormField control={twoFactorForm.control} name="code" render={({ field }) => <div className="space-y-2"><Label htmlFor="2fa-code">Authentication code</Label><Input id="2fa-code" placeholder="000000" maxLength={6} autoComplete="one-time-code" inputMode="numeric" className="h-14 text-center font-mono text-2xl tracking-[0.35em]" {...field} onChange={(event) => field.onChange(event.target.value.replace(/\D/g, "").slice(0, 6))} /><FormMessage /></div>} />
            {apiError && <p className="rounded-lg border border-destructive/20 bg-destructive/5 p-3 text-xs font-medium text-destructive">{apiError}</p>}
            <Button type="submit" size="lg" className="w-full" disabled={twoFactorForm.formState.isSubmitting}>{twoFactorForm.formState.isSubmitting ? "Verifying…" : <>Verify access <ArrowRight /></>}</Button>
            <button type="button" onClick={back} className="flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5" />Back to credentials</button>
          </form>
        </Form>
      ) : (
        <Form {...loginForm}>
          <form className="space-y-5" onSubmit={loginForm.handleSubmit(onSubmitLogin)}>
            <FormField control={loginForm.control} name="email" render={({ field }) => <div className="space-y-2"><Label htmlFor="login-email">Work email</Label><Input id="login-email" type="email" placeholder="name@company.com" autoComplete="email" {...field} /><FormMessage /></div>} />
            <FormField control={loginForm.control} name="password" render={({ field }) => <div className="space-y-2"><div className="flex items-center justify-between"><Label htmlFor="login-password">Password</Label><Link href="/forgot-password" className="text-xs font-semibold text-primary hover:underline">Forgot password?</Link></div><Input id="login-password" type="password" placeholder="••••••••" autoComplete="current-password" {...field} /><FormMessage /></div>} />
            {apiError && <p className="rounded-lg border border-destructive/20 bg-destructive/5 p-3 text-xs font-medium text-destructive">{apiError}</p>}
            <Button type="submit" size="lg" className="w-full" disabled={loginForm.formState.isSubmitting}>{loginForm.formState.isSubmitting ? "Opening workspace…" : <>Enter workspace <ArrowRight /></>}</Button>
          </form>
        </Form>
      )}
    </AuthShell>
  );
}
